"""Initial migration

Revision ID: 759b737b0c9c
Revises: 
Create Date: 2026-07-07 01:03:20.652549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759b737b0c9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bon_livraison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('date_livraison', sa.DateTime(), nullable=True),
    sa.Column('date_piece', sa.DateTime(), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('total_ht', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_tva', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_ttc', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('est_valider', sa.Boolean(), nullable=True),
    sa.Column('est_imprimer', sa.Boolean(), nullable=True),
    sa.Column('est_envoyer', sa.Boolean(), nullable=True),
    sa.Column('est_desactive', sa.Boolean(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('mode_livraison_id', sa.Integer(), nullable=True),
    sa.Column('adresse_livraison', sa.String(length=255), nullable=True),
    sa.Column('code_postal_livraison', sa.String(length=20), nullable=True),
    sa.Column('societe_livraison', sa.String(length=255), nullable=True),
    sa.Column('transporteur', sa.String(length=150), nullable=True),
    sa.Column('numero_suivi', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('portable', sa.String(length=30), nullable=True),
    sa.Column('numero_tva', sa.String(length=50), nullable=True),
    sa.Column('siret', sa.String(length=50), nullable=True),
    sa.Column('site_web', sa.String(length=255), nullable=True),
    sa.Column('est_bloquer', sa.Boolean(), nullable=True),
    sa.Column('est_pospect', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.Column('famille_id', sa.Integer(), nullable=True),
    sa.Column('mode_reglement_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('famille_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('est_service', sa.Boolean(), nullable=True),
    sa.Column('est_default', sa.Boolean(), nullable=True),
    sa.Column('est_desactive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('libelle', sa.String(length=100), nullable=True),
    sa.Column('valeur', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('est_default', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adresse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('complement', sa.String(length=255), nullable=True),
    sa.Column('ville_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('societe', sa.String(length=255), nullable=True),
    sa.Column('est_default', sa.Boolean(), nullable=True),
    sa.Column('est_livraison', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lien', sa.String(length=500), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('est_attache_email', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reglement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('montant_regle', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('est_encaisser', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type_paiement_id', sa.Integer(), nullable=True),
    sa.Column('mode_rgelement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('sous_famille_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('famille_article_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('est_default', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['famille_article_id'], ['famille_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.String(length=255), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('date_token', sa.DateTime(), nullable=True),
    sa.Column('code_verification', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('est_bloque', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prix_vente_ht', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prix_vente_ttc', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('est_affiche_ttc', sa.Boolean(), nullable=True),
    sa.Column('est_service', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('est_bloque', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.Column('tva_id', sa.Integer(), nullable=True),
    sa.Column('famille_article_id', sa.Integer(), nullable=True),
    sa.Column('sous_famille_article_id', sa.Integer(), nullable=True),
    sa.Column('unite_id', sa.Integer(), nullable=True),
    sa.Column('stock_disponible', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['famille_article_id'], ['famille_article.id'], ),
    sa.ForeignKeyConstraint(['sous_famille_article_id'], ['sous_famille_article.id'], ),
    sa.ForeignKeyConstraint(['tva_id'], ['tva.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('date_commande', sa.DateTime(), nullable=True),
    sa.Column('date_piece', sa.DateTime(), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('total_ht', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_tva', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_ttc', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('est_valider', sa.Boolean(), nullable=True),
    sa.Column('est_solder', sa.Boolean(), nullable=True),
    sa.Column('montant_regle', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('solde_du', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('detail_reglement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reglement_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('type_piece', sa.String(length=50), nullable=True),
    sa.Column('montant', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('numero_piece', sa.String(length=50), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reglement_id'], ['reglement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('date_facture', sa.DateTime(), nullable=True),
    sa.Column('date_piece', sa.DateTime(), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('total_ht', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_tva', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_ttc', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('est_valider', sa.Boolean(), nullable=True),
    sa.Column('est_solder', sa.Boolean(), nullable=True),
    sa.Column('montant_regle', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('solde_du', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entite_type', sa.String(length=50), nullable=True),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('lien', sa.String(length=500), nullable=True),
    sa.Column('entite_type', sa.String(length=50), nullable=True),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('est_lu', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('est_valide', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piece_jointe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entite_type', sa.String(length=50), nullable=False),
    sa.Column('entite_id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('lien', sa.String(length=500), nullable=False),
    sa.Column('type_mime', sa.String(length=100), nullable=True),
    sa.Column('taille', sa.Integer(), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.Column('uploade_par_id', sa.Integer(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uploade_par_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('sujet', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('priorite', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('piece_liee_id', sa.Integer(), nullable=True),
    sa.Column('type_piece_liee', sa.String(length=50), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('article_bon_livraison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('nom_article', sa.String(length=255), nullable=True),
    sa.Column('code_article', sa.String(length=100), nullable=True),
    sa.Column('quantite', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantite_transferer', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prix_ht', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prix_ttc', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_prix_ht', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_prix_ttc', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valeur_tva', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('est_sous_total', sa.Boolean(), nullable=True),
    sa.Column('est_desactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['bon_livraison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('nom_article', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('quantite', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prix_ht', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prix_ttc', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_prix_ht', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_prix_ttc', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valeur_tva', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_valeur_tva', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('taux_remise', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valeur_remise', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('est_commentaire', sa.Boolean(), nullable=True),
    sa.Column('est_sous_total', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['commande.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('nom_article', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('quantite', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prix_ht', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prix_ttc', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_prix_ht', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_prix_ttc', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valeur_tva', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_valeur_tva', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('taux_remise', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valeur_remise', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('est_commentaire', sa.Boolean(), nullable=True),
    sa.Column('est_sous_total', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['facture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_panier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panier_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('prix_ht', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('prix_ttc', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['panier_id'], ['panier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_statut_commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('ancien_status_id', sa.Integer(), nullable=True),
    sa.Column('nouveau_status_id', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_changement', sa.DateTime(), nullable=True),
    sa.Column('modifie_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commande.id'], ),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('auteur_client', sa.Boolean(), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.Column('est_lu', sa.Boolean(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_ticket')
    op.drop_table('historique_statut_commande')
    op.drop_table('article_panier')
    op.drop_table('article_facture')
    op.drop_table('article_commande')
    op.drop_table('article_bon_livraison')
    op.drop_table('ticket')
    op.drop_table('piece_jointe')
    op.drop_table('panier')
    op.drop_table('notification')
    op.drop_table('journal_audit')
    op.drop_table('facture')
    op.drop_table('detail_reglement')
    op.drop_table('commande')
    op.drop_table('article')
    op.drop_table('utilisateur')
    op.drop_table('sous_famille_article')
    op.drop_table('reglement')
    op.drop_table('document')
    op.drop_table('adresse')
    op.drop_table('tva')
    op.drop_table('famille_article')
    op.drop_table('client')
    op.drop_table('bon_livraison')
    # ### end Alembic commands ###
